name: build
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pip install -U -r requirements.txt

      - name: Build and check for errors
        run: mkdocs build --strict

      - name: Deploy docs
        if: github.ref_name == 'master'
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

